package com.example.flatbuffers.app.flatmodel;// automatically generated by the FlatBuffers compiler, do not modify

import java.nio.*;
import java.lang.*;
import java.util.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Developer extends Table {
    public static Developer getRootAsDeveloper(ByteBuffer _bb) {
        return getRootAsDeveloper(_bb, new Developer());
    }

    public static Developer getRootAsDeveloper(ByteBuffer _bb, Developer obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public Developer __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public long id() {
        int o = __offset(4);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public String firstName() {
        int o = __offset(6);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer firstNameAsByteBuffer() {
        return __vector_as_bytebuffer(6, 1);
    }

    public String lastName() {
        int o = __offset(8);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer lastNameAsByteBuffer() {
        return __vector_as_bytebuffer(8, 1);
    }

    public int age() {
        int o = __offset(10);
        return o != 0 ? bb.getInt(o + bb_pos) : 0;
    }

    public String gender() {
        int o = __offset(12);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer genderAsByteBuffer() {
        return __vector_as_bytebuffer(12, 1);
    }

    public String email() {
        int o = __offset(14);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer emailAsByteBuffer() {
        return __vector_as_bytebuffer(14, 1);
    }

    public String skill() {
        int o = __offset(16);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer skillAsByteBuffer() {
        return __vector_as_bytebuffer(16, 1);
    }

    public Friend friends(int j) {
        return friends(new Friend(), j);
    }

    public Friend friends(Friend obj, int j) {
        int o = __offset(18);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int friendsLength() {
        int o = __offset(18);
        return o != 0 ? __vector_len(o) : 0;
    }

    public static int createDeveloper(FlatBufferBuilder builder,
                                      long id,
                                      int first_nameOffset,
                                      int last_nameOffset,
                                      int age,
                                      int genderOffset,
                                      int emailOffset,
                                      int skillOffset,
                                      int friendsOffset) {
        builder.startObject(8);
        Developer.addId(builder, id);
        Developer.addFriends(builder, friendsOffset);
        Developer.addSkill(builder, skillOffset);
        Developer.addEmail(builder, emailOffset);
        Developer.addGender(builder, genderOffset);
        Developer.addAge(builder, age);
        Developer.addLastName(builder, last_nameOffset);
        Developer.addFirstName(builder, first_nameOffset);
        return Developer.endDeveloper(builder);
    }

    public static void startDeveloper(FlatBufferBuilder builder) {
        builder.startObject(8);
    }

    public static void addId(FlatBufferBuilder builder, long id) {
        builder.addLong(0, id, 0L);
    }

    public static void addFirstName(FlatBufferBuilder builder, int firstNameOffset) {
        builder.addOffset(1, firstNameOffset, 0);
    }

    public static void addLastName(FlatBufferBuilder builder, int lastNameOffset) {
        builder.addOffset(2, lastNameOffset, 0);
    }

    public static void addAge(FlatBufferBuilder builder, int age) {
        builder.addInt(3, age, 0);
    }

    public static void addGender(FlatBufferBuilder builder, int genderOffset) {
        builder.addOffset(4, genderOffset, 0);
    }

    public static void addEmail(FlatBufferBuilder builder, int emailOffset) {
        builder.addOffset(5, emailOffset, 0);
    }

    public static void addSkill(FlatBufferBuilder builder, int skillOffset) {
        builder.addOffset(6, skillOffset, 0);
    }

    public static void addFriends(FlatBufferBuilder builder, int friendsOffset) {
        builder.addOffset(7, friendsOffset, 0);
    }

    public static int createFriendsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startFriendsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static int endDeveloper(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }
}

